[package]
name = "set-up-spaces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_runtime = "0.131.0"
tokio = { version = "1", features = ["full"] }
